// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cheohgftqntooewvxrns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZW9oZ2Z0cW50b29ld3Z4cm5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNjcxNTEsImV4cCI6MjA1NTY0MzE1MX0.llbQ8OeyfoJlIEF06BygzJA7qxAR1ixX5D0hgBTNCts";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);